name: Sync with GitLab

on:
  schedule:
    - cron: '33 3 * * *' # Runs daily at 3:33 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history

      - name: Set up Git
        run: |
          git config --global user.name 'Trahloc'
          git config --global user.email 'github-com@trahloc.com'

      - name: Add GitLab Remote
        run: |
          git remote add gitlab https://github.com/Trahloc/midi-qol.git || true

      - name: Fetch All Branches from GitLab
        run: git fetch gitlab --prune

      - name: Force Sync All Branches to GitHub
        run: |
          for branch in $(git branch -r | grep 'gitlab/' | sed 's|gitlab/||' | grep -v 'HEAD'); do
            echo "Syncing branch: $branch"
            git checkout -B "$branch" "gitlab/$branch"
            git push --force origin "$branch"
          done
